services:
  treafik:
    container_name: traefik
    image: traefik:v3.5.3
    user: "${BENDIT_UID}:${BENDIT_GID}"
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ${TRAEFIK_CONF_PATH}/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true

