- name: Base user setup
  become: yes
  hosts: bendit-core
  tasks:
    - name: Create ansible lock files directory
      ansible.builtin.file:
        state: directory
        path: /home/bendit/ansible_locks
        owner: bendit
        group: bendit
        mode: 0750

    - name: Create secrets directory
      ansible.builtin.file:
        state: directory
        path: /home/bendit/.secrets
        owner: bendit
        group: bendit
        mode: 0750

    - name: Create services directory
      ansible.builtin.file:
        state: directory
        path: /home/bendit/services
        owner: bendit
        group: bendit
        mode: 0750

- name: Install Docker
  become: yes
  hosts: bendit-core
  tasks:
    - name: Check if Docker install_docker.lock file exists
      ansible.builtin.stat:
        path: /home/bendit/ansible_locks/install_docker.lock
      register: lock_stat

    - name: Download Docker key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker.asc
        mode: 0644
      when: not lock_stat.stat.exists

    - name: Add apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        filename: docker
      when: not lock_stat.stat.exists

    - name: Install Docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes
      when: not lock_stat.stat.exists

    - name: Add users to Docker group
      ansible.builtin.user:
        name: bendit
        append: true
        groups: docker
      when: not lock_stat.stat.exists

    - name: Create lock file
      ansible.builtin.file:
        state: touch
        path: /home/bendit/ansible_locks/install_docker.lock
        owner: bendit
        group: bendit
        mode: 0640
      when: not lock_stat.stat.exists

- name: Configure services
  hosts: bendit-core
  become: yes
  tasks:
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: ../services/docker-compose.yaml
        dest: /home/bendit/services/docker-compose.yaml
        owner: bendit
        group: bendit
        mode: 0640

    - name: Copy treafik config
      ansible.builtin.copy:
        src: ../services/traefik.yaml
        dest: /home/bendit/services/traefik.yaml
        owner: bendit
        group: bendit
        mode: 0640

    - name: Copy run_service.sh file
      ansible.builtin.copy:
        src: ../services/run_service.sh
        dest: /home/bendit/services/run_service.sh
        owner: bendit
        group: bendit
        mode: 0750

    - name: Run services
      ansible.builtin.command: ./run_service.sh all
      become: yes
      become_user: bendit
      args:
        chdir: /home/bendit/services
